#+TITLE: Usage
#+AUTHOR: Juho Snellman
#+EMAIL: jsnell@iki.fi
#+STYLE: <link rel="stylesheet" type="text/css" href="stc/org.css" />

* Questions

Do you have questions that this document doesn't answer? A good place
to ask is the [[http://boardgamegeek.com/article/11807989][PBF moderator help / questions]]
thread on BGG. There are a lot people who know how to use the
moderator, so there's a good chance you'll get an answer faster than
by contacting me directly.

* New Games

** Creating a Game

To create a new game, you'll need to be logged in. After that, you'll
be able to create a game from the [[http://terra.snellman.net/newgame/][New Game]] page. You'll be redirected
to the admin page of the new game, and can use that to finish the
setup (e.g. listing the players). Any new games will also appear on 
the front page under "your games", with the "admin" role.

After faction selection is done, the admin page of the game will
also have a link for each faction. These links allow entering moves
for that single faction, but not editing the game history or making
moves for other factions. You can distribute these links to the
players if you want them to do their own move entry.

** Setting up the Game

During setup, you'll need the following sections in the game file,
some of which will have been randomly set up when the game was created.
You can still edit them, if you want.

List the players (in any order, it will get randomized):

#+BEGIN_EXAMPLE
  player Alice email alice@example.com
  player Bob email bob@example.com
  player Charlie
#+END_EXAMPLE

Randomize the player order, scoring tiles, and remove the appropriate
number of bonus tiles.

#+BEGIN_EXAMPLE
  randomize v1 seed game1324
#+END_EXAMPLE

Select the factions in play:

#+BEGIN_EXAMPLE
  # Faction selection
  setup Nomads for Alice
  setup Auren for Bob
  setup Swarmlings for Charlie
#+END_EXAMPLE

Place initial dwellings:

#+BEGIN_EXAMPLE
  Nomads: Build A5
  Auren: Build F4
  Swarmlings: Build H4. Build G6
  Auren: Build F2
  Nomads: Build B4. Build G7
#+END_EXAMPLE

Select initial bonus tiles:

#+BEGIN_EXAMPLE
  Swarmlings: Pass Bon8
  Auren: Pass Bon2
  Nomads: Pass Bon5
#+END_EXAMPLE

The game will then automatically start.

* Commands

When using the full admin interface, each line should start with the
name of the faction that's doing stuff, followed by a colon. When
using the more limited per-faction interface, no such prefix should
be added -- it'll automatically apply the commands to the current
faction.

After this, you can have multiple commands that apply to that faction,
separated by full stops. *Every line should consist of exactly a single turn*.
Do not split a single turn across multiple lines, or merge multiple
turns on a single line.

For example:

#+BEGIN_EXAMPLE
  Nomads: Dig 1. Build E7
#+END_EXAMPLE

The exact capitalization doesn't matter. 

The commands that you'd usually use are:

** =pass= /tile/

Example: =pass bon2=

Pass, return current bonus tile, and replace it with Bon2. When passing
on the last turn, leave out the bonus tile name.

** =leech= /amount/ =from= /faction/

Example: =Leech 2=.

Trade 1 vp for 2 power

Example: =Leech 1 from fakirs=

Trade no vps for 1 power, using the opportunity provided by the Fakirs
rather than some other faction (in case there are multiple opportunities
available).

** =decline= /amount/ =from= /faction/

Example: =decline=.

Decline all outstanding trades of vp to power

Example: =decline 1 from cultists=

Decline just the offer of 1 power from the cultists.

** =action= /label/

Example: =action act5=

Take the power action 5 (or stronghold, bonus
tile, or favor special action).

** =dig= /amount/

Example: =dig 1=. 

Trade workers / priests to shovels at the appropriate exchange rate.
The shovels need to be spent by commands later on the same line.

** =build= /location/

Example: =build F5=

Terraform the hex F5 into the correct terrain type, and build a
dwelling there.

** =upgrade= /location/ =to= /building/

Example: =upgrade F5 to TP=

Replace the dwelling in F5 with a trading post (TE for temples, SH for
strongholds, SA for sanctuaries).

** =send P to= /cult/ =for= /amount/

Example: =Send P to Fire=

Send a priest to the first free spot on the fire cult track.

By default the best available slot on the track is used. The optional
"for X" part of the command can be used to use a different slot, or
no slot at all.

Example: =Send P to Water for 1=

Send a priest to the water cult, taking just one level of advancement
(even if 2 or 3 slots are still remaining).

** =transform= /location/ =to= /color/

Example: =transform F5 to black=

Terraform F5 to black, but don't build anything there.

** =convert= /amount/ /resource/ =to= /amount/ /resource/

Example: =convert 3pw to 1w=

Convert between resources.

** =burn= /amount/

Example: =burn 2=

Remove 2 power from bowl 2, and move 2 power from bowl 2 to 3.

** + /amount/ /resource/ or - /amount/ /resource/

Example: =+FAV11=

Take the Favor tile #11. (TW3 for Town tile 3, you shouldn't take
Bonus tiles with +, but use the Pass command). 

Example: =-4w=

Return 4 workers from the treasury to the pool.

** =bridge= /location:location/

Example: =Bridge E9:D6=

Build a bridge from E9 to D6.

** =advance= /track/

Example: =advance ship=

Advance 1 step on the shipping track. "Advance dig" for improving the
shovel track.

** =setup= /faction/ =for= /player/ =email= /address/

Example:
#+BEGIN_EXAMPLE
setup Nomads for Alice
#+END_EXAMPLE

Add this faction to the game. The player name is optional, you also do just
=setup Nomads=.

Example:
#+BEGIN_EXAMPLE
setup Nomads for Alice email alice@example.com
#+END_EXAMPLE

For a PBEM game, associate the email address with this faction. Gets
added to the list of addresses that the "send email" functionality sends
email to, except those sent by this faction.


* Obscure commands

** =admin email= /email/

Give another user full admin rights to the game.

** =income=

/Note/: This command is only needed if you absolutely want to take income
before all open decisions (e.g. power leeching) have been made. You should generally not
need it.

#+BEGIN_EXAMPLE
  income
#+END_EXAMPLE
#+BEGIN_EXAMPLE
  Nomads: income
#+END_EXAMPLE

Take all income (buildings, favors, bonus tiles, last turn's special
scoring tile) for either all players (if no faction specified), or a
specific faction. Should be done just before =start=-ing a new round.

** =start=

/Note/: This command is only needed if you want to start a new round
before all the decisions from the previous round (e.g. using spades
gained from cult bonuses) are done. You should not need it.

Move to the next round.

** =finish=

Do the final scoring. You can also trigger the final scoring by just
declining or accepting any remaining offers of power, once all players
have passed on the final round.

** =email= /email addresses/

Example: =email alice@example.com,bob@example.com,charlie@example.com=

List the email addresses associated with the game. These addresses
get added to all emails sent by the game. Useful mainly if you want
all game-related traffic to go to a specific mailing list. Usually
it's better to associate addresses with individual factions.

* Notes on specific factions

** Mermaids

The mermaid special town founding ability can't be used automatically,
but must be triggered manually. Use the =connect= command to mark
hexes that should be considered adjacent for this purpose. For example
if the mermaids declare the river hex between F2 and E4 as the one
they want to skip, use the command =connect F2:E4=). If there are multiple
valid river hexes, the tracker will pick an arbitrary one. If you
want to specify the river hex exactly, specify 3 land hexes:
=connect G2:H4:I6=.

** Darklings

To use the power of the Darkling Stronghold, use a command like
=convert 3w to 3p=. Note that this special exchange rate is only valid
until the end of the line on which the Stronghold was built.

** Nomads

The sandstorm ability of the Nomad Stronghold has some limits that
aren't yet automatically checked. Specifically, it needs direct land
adjacency. No ships, no bridges. The human moderator and other players
should check that this constraint isn't broken.

** Dwarves / Fakirs

The system will automatically detect if the Dwarves / Fakirs may use
their special tunneling or carpet flight, and handles the resource costs
and VP gains without any additional input.

Note that a strict reading of the rules doesn't allow for using
these abilities when spending spades from a scoring tile, nor using
the power twice (for separate hexes) when gaining two spades from
ACT6. These constraints are not automatically checked.

** Chaos Magicians

When using the Chaos Magician Stronghold, please put all 3 actions
(taking the action, and the two extra actions that follow) on the same
line. The system doesn't actually track this ability, and gets
confused about turn order if the commands are split on multiple lines.

** Giants

It's possible for Giants to receive a single spade from a cult scoring
bonus, and be unable to spend it (due to always needing exactly
two spades for any transforming). To advance, throw away the spade with
=-SPADE=.

** Engineers

To build a bridge with the engineer special ability, use the =convert=
command: =convert 2w to bridge. bridge h6:i9=

* Known issues and workarounds

** FAV5 tile

Problem: The tracker doesn't correctly account for a situation where:
taking FAV5 triggers a formation of the town, the player has a fire
cult level of 8 or 9 before taking the favor tile, and doesn't have
sufficient keys to advance to the 10 spot. The end result is supposed
to be that the player may advance to the 10 spot immediately.

Solution: Just add a single =+FIRE= command after taking the town tile.

** TW5 tile

Problem: When taking the TW5 tile, a player who is on the 9 spot on
multiple tracks can't choose which cult track to advance to 10 on. Instead
the game will advance him to 10 on an arbitrary track.

Solution: Before taking the town tile, move the player down a step on
the cult tracks he doesn't want to advance to 10 on (for example
=-WATER=). Note that you should do this adjustment first, doing it
after taking the town tile will unjustly award 3 power to the player.





* Browser and Email Setup

The "Send email" functionality works by opening a pre-formatted email
message in your normal email program, addressed to the other players.
This only works if your browser is configured to use the correct email
program. It should work by default at least on Android devices, iPhones
and iPads. This section lists hints to configuring some common browsers
or mail programs.

** Gmail and Chrome

To get Chrome to automatically open the message in Gmail, rather than 
in a desktop mailer, follow these instructions from Google:

https://support.google.com/chrome/bin/answer.py?hl=en&answer=1382847&p=ib_protocol_handler

** Outlook

Outlook uses the semicolon as the address separator rather than the
standard comma. The workaround is to toggle the =Allow comma as
address separator= option in Outlook, as described here
<http://support.microsoft.com/kb/820868>.

** Internet Explorer 6/7/8

IE8 or earlier are not supported. You'll unfortunately need to do one of:

- Upgrade to IE9
- Install another browser
- Install the Chrome Frame plugin from http://www.google.com/chromeframe

