#+TITLE: User's Guide for Online Terra Mystica
#+AUTHOR: Juho Snellman
#+EMAIL: jsnell@iki.fi
#+STYLE: <link rel="stylesheet" type="text/css" href="stc/org.css" />

* Bug Reports

Is something not working correctly, or in the way you expect? Please
let me know by [[mailto:jsnell@iki.fi][email at jsnell@iki.fi]]. There is almost no chance of
bugs getting fixed if I don't hear about them. Please include the
following information with the report:

- Your username
- Name of the game (if the bug appears on the game page)

* Questions

Do you have questions that this document doesn't answer? A good place
to ask is the [[http://boardgamegeek.com/article/11807989][PBF moderator help / questions]]
thread on BGG. There are a lot people who know how to use the
moderator, so there's a good chance you'll get an answer faster than
by contacting me directly.

* Playing the Game

# <<join-game>
** Joining a Game

To join an open public game, go to [[/joingame/][list of open games]], and click the
"join" button. Please be considerate to the other players: if the
description section lists any special requirements, only join the game
if you can fulfill the requirements. If no suitable games are open,
just create a new one.

** Playing a Game

The game page consists of several sections, from top to bottom:

- Map: The game map and cult tracks.
- Status display: Whose turn is it, and what should they be doing?
- Entry: Enter your moves, future plans, chat messages etc. here
- Faction information: The individual player boards. Your board will always show up topmost for convenience.
- Resource pool: Shows the unclaimed shared resources, such as power actions and various kinds of tiles
- Ledger: A detailed game history

Most of these sections should be self-explanatary. The less obvious
parts are explained in more detail below.

*** Abbreviations

The game uses the following abbreviations for resources, building
types and iconography. The capitalization doesn't matter, and is
simply a matter of convention:

- =c=: Coin
- =w=: Worker 
- =pw=: Power
- =p=: Priest
- =vp=: Victory point

- =D=: Dwelling
- =TP=: Trading House
- =TE=: Temple
- =SH=: Stronghold
- =SA=: Sanctuary

- =pass-vp=: Victory points gained when passing
- =>>=: Victory points gained during the round
- =spd=, =spade=: A spade
- =+=: Gained during the income phase
- =cult=: A step on any cult track

*** Entry

The entry section contains 4 tabs:

**** Moves

For entering your moves. On the left-hand side is a text-box into which you can enter the [[gameplay-commands][commands]] corresponding to your moves. On the right is a UI for entering commands more conveniently than by typing them.

After you've entered your moves, click on =Preview= to see the effect of the commands. If the moves were valid and you're happy with then, click =Save= to advance the game to the next player.

Note that you can't =Save= if you still need to enter more moves. If you want to wait for a reaction from some other player, use the =wait= command.

**** Planning

For leaving notes for yourself, or to plan your coming moves using the
same input format as for normal play. View the effects of the plan
with =Show result= or save the plan / notes for later with =Save plan=.

**** Recent Moves

Shows a summary of what happened since your last move.

**** Chat

The in-game chat.

*** Faction Information

The faction information section shows the following information for
each faction. On the left:

- Current resource levels. (For power interpret =7/5/0= as 7 power in bowl I, 5 power in bowl II, and none in bowl III). You can click on the =vp= resource to see a breakdown of where that factions victory points have come from.
- The current and maximum levels of the digging and shipping tracks (for factions where that's applicable). For Dwarves and Fakirs the current tunneling / carpet flight range is shown instead.
- The current and maximum amounts of each building type. If you're at the maximum number of dwellings or trading houses, the number will be highlighted in red. Click on the =+= icon to show build / upgrade costs for each building type, as well as the income that the new building generates. (Note, the income lost due to the upgrade is not shown).
- The expected income of the 4 most important resources in the next income phase. Click on =+= to see a breakdown of where the income comes from.
- On the final round the income is replaced with a VP projection instead. Click on =+= to see a breakdown of where the additional VPs are coming from.

On the right:

- The terrain wheel of the faction
- The special actions available for this faction
- The tiles the faction owns

*** Ledger

The ledger shows a detailed full history of the game. There are two kinds
of rows in the table. Comments are shown in a bold font. The other rows
correspond to individual player turns. These rows have the following
elements in this order:

- The faction who did the action
- The change in resources (and final value) caused by the move. The change is shown in black, the final value in light gray. The resources are, in order, victory points, coins, workers, priests, power in the 3 bowls, and steps on the 4 cult tracks.
- The power leeching opportunities given to other players by this move
- The commands corresponding to the turn

Click on =show history= to switch the game view to what it was during
that point in the game.

#<<gameplay-commands>>
** Gameplay Commands

The following commands are available during gameplay. They can be entered
either one per line, or on the same line separated by dots.

When entering the through the admin interface, prefix the command with
the name of the faction doing the command.

*** =pass= /tile/

Example: =pass bon2=

Pass, return current bonus tile, and replace it with Bon2. When passing
on the last turn, leave out the bonus tile name.

*** =leech= /amount/ =from= /faction/

Example: =Leech 2=.

Trade 1 vp for 2 power

Example: =Leech 1 from fakirs=

Trade no vps for 1 power, using the opportunity provided by the Fakirs
rather than some other faction (in case there are multiple opportunities
available).

*** =decline= /amount/ =from= /faction/

Example: =decline=.

Decline all outstanding trades of vp to power

Example: =decline 1 from cultists=

Decline just the offer of 1 power from the cultists.

*** =action= /label/

Example: =action act5=

Take the power action 5 (or stronghold, bonus
tile, or favor special action).

*** =dig= /amount/

Example: =dig 1=. 

Trade workers / priests to shovels at the appropriate exchange rate.
The shovels need to be spent by commands later on the same line.

*** =build= /location/

Example: =build F5=

Terraform the hex F5 into the correct terrain type, and build a
dwelling there.

*** =upgrade= /location/ =to= /building/

Example: =upgrade F5 to TP=

Replace the dwelling in F5 with a trading post (TE for temples, SH for
strongholds, SA for sanctuaries).

*** =send P to= /cult/ =for= /amount/

Example: =Send P to Fire=

Send a priest to the first free spot on the fire cult track.

By default the best available slot on the track is used. The optional
"for X" part of the command can be used to use a different slot, or
no slot at all.

Example: =Send P to Water for 1=

Send a priest to the water cult, taking just one level of advancement
(even if 2 or 3 slots are still remaining).

*** =transform= /location/ =to= /color/

Example: =transform F5 to black=

Terraform F5 to black, but don't build anything there. The color
to transform to is optional, you can also do just:

Example: =transform F5=

In this case the hex is transformed either to your home color, or
as close to it as possible given the available spades.

*** =convert= /amount/ /resource/ =to= /amount/ /resource/

Example: =convert 3pw to 1w=

Convert between resources.

*** =burn= /amount/

Example: =burn 2=

Remove 2 power from bowl 2, and move 2 power from bowl 2 to 3.

*** + /amount/ /resource/ or - /amount/ /resource/

Example: =+FAV11=

Take the Favor tile #11. (TW3 for Town tile 3, you shouldn't take
Bonus tiles with +, but use the Pass command). 

Example: =-4w=

Return 4 workers from the treasury to the pool.

*** =bridge= /location:location/

Example: =Bridge E9:D6=

Build a bridge from E9 to D6.

*** =advance= /track/

Example: =advance ship=

Advance 1 step on the shipping track. "Advance dig" for improving the
shovel track.

*** =wait=
Example:
#+BEGIN_EXAMPLE
Wait
#+END_EXAMPLE

Wait for other players to react. Useful for example if you're the
last player who hasn't passed, and want to see whether another player
accepts power between two of your moves.

*** =done=
Example:
#+BEGIN_EXAMPLE
Done
#+END_EXAMPLE

Finish your turn. Useful mostly when you're the only player who hasn't passed,
and want to break the chain of actions at a specific place. For example
when using Dwarves or Fakirs to first tunnel to a space to terraform it,
and right afterwards tunnel to the same space to build a dwelling.


*** =setup= /faction/ =for= /player/

Example:
#+BEGIN_EXAMPLE
setup Nomads for Alice
#+END_EXAMPLE

Add this faction to the game. The player name is optional, you also do just
=setup Nomads=.

*** =#=

Example:
#+BEGIN_EXAMPLE
# This text is ignored
#+END_EXAMPLE

Ignore the remainder of the line. Useful mostly in the planning tool --
you can use comments to interleave notes to yourself and actual commands.

* Running Games

** Making a New Game

To create a new game, you'll need to be logged in. After that, you'll
be able to create a game from the [[http://terra.snellman.net/newgame/][New Game]] page. The system supports
two types of games, public and private. Additionally you can select
which [[options]] to include in the game.

- In private games all the players are specified up front when
  creating a game. The preferred method of doing this is by the
  username of the players. It's good etiquette to not anyone to a
  private game unless they're expecting it.

- Public games are games that anyone can join. The game starts as soon
  as enough people have [[join-game][joined]] it. Email notifications must always be
  turned on for public games.

** Administrating the Game

The creator of the game has administrator rights to the game, and can
edit the history arbitrarily. You can find the admin section of the
games you run under the "Games you Administrate" section on the home
page.

The admin section is useful for example in the following circumstances:

- A player misenters an order and would like to undo it. It's up to the game creator to decide under which circumstances a rollback is reasonable.
- You wish to stop the game prematurely. This can be done with the [[abort]] command.

Note that the administrator rights only apply to the game itself. Most
importantly the admin can't read the planning notes of other players.


#<<admin-commands>>
** Administrative commands

The following commands are available for changing the state of the game.

# <<options>>
*** =option= /option/

Example:
#+BEGIN_EXAMPLE
  option errata-cultist-power
#+END_EXAMPLE

Set a game variant or option. Should be done before randomization or
faction selection. The following options are available:

- =errata-cultist-power=: Official rules change, http://boardgamegeek.com/thread/1009456/rules-update-for-cultists
- =mini-expansion-1=: First mini-expansion, 4 town tiles
- =shipping-bonus=: Additional bonus tile from Spielbox 6/2013, http://boardgamegeek.com/image/1843355/terra-mystica-navigation-round-bonus-tile
- =email-notify=: Automatically send email notifications after moves (players can configure exactly which emails they want to see). Can't be used in games with unregistered players.
- =strict-leech=: Validate that any 'leech' commands by a single player happen in the correct order. This option is on by default for new games. Turning it off is not recommended.

*** =abort=

Forcibly end the game. Useful for hiding a stalled game from the "your
games" list.



* Notes on specific factions

** Mermaids

The mermaid special town founding ability can't be used automatically,
but must be triggered manually. Use the =connect= command to mark
hexes that should be considered adjacent for this purpose. For example
if the mermaids declare the river hex between F2 and E4 as the one
they want to skip, use the command =connect F2:E4=). If there are multiple
valid river hexes, the tracker will pick an arbitrary one. If you
want to specify the river hex exactly, specify 3 land hexes:
=connect G2:H4:I6=.

** Darklings

To use the power of the Darkling Stronghold, use a command like
=convert 3w to 3p=. Note that this special exchange rate is only valid
for the duration of the turn.

** Dwarves / Fakirs

The system will automatically detect if the Dwarves / Fakirs may use
their special tunneling or carpet flight, and handles the resource costs
and VP gains without any additional input.

See the =done= command for splitting up transforming and building into
separate actions.

** Giants

It's possible for Giants to receive a single spade from a cult scoring
bonus, and be unable to spend it (due to always needing exactly
two spades for any transforming). To advance, throw away the spade with
=-SPADE=.

** Engineers

To build a bridge with the engineer special ability, use the =convert=
command: =convert 2w to bridge. bridge h6:i9=

* Known issues and workarounds

** FAV5 tile

Problem: The tracker doesn't correctly account for a situation where:
taking FAV5 triggers a formation of the town, the player has a fire
cult level of 8 or 9 before taking the favor tile, and doesn't have
sufficient keys to advance to the 10 spot. The end result is supposed
to be that the player may advance to the 10 spot immediately.

Solution: Just add a single =+FIRE= command after taking the town tile.

** TW5 tile

Problem: When taking the TW5 tile, a player who is on the 9 spot on
multiple tracks can't choose which cult track to advance to 10 on. Instead
the game will advance him to 10 on an arbitrary track.

Solution: Before taking the town tile, move the player down a step on
the cult tracks he doesn't want to advance to 10 on (for example
=-WATER=). Note that you should do this adjustment first, doing it
after taking the town tile will unjustly award 3 power to the player.





# <<keyboard-shortcuts>>
* Keyboard shortcuts

The application has a small number of keyboard shortcuts defined for
navigating the interface. To trigger the shortcut, you need to combine
it with a browser-dependent modifier key, for example "Alt" on Chrome
or "Alt-Shift" on Firefox. See http://en.wikipedia.org/wiki/Access_key
for information on which modifier key is used by your browser and
operating system.

The following shortcuts are defined on most views, such as the game view
and the game list:

- =h= (home): Return to the home page / list of games.
- =n= (next game): Refresh game information. Go to next game where it's your turn to move.

The following additional keyboard shortcuts are defined only in the game
view:

- =m= (moves): Switch to the moves tab
- =p= (planning): Switch to the planning / notes tab
- =r= (recent): Switch to the recent moves tab
- =c= (chat): Switch to the chat tab


* Browser and Email Setup

This section applies to the older "Send email" functionality, which is
available for games where automatic email notifications are not
enabled. 

The feature works by opening a pre-formatted email message in your
normal email program, addressed to the other players.  This only works
if your browser is configured to use the correct email program. It
should work by default at least on Android devices, iPhones and
iPads. This section lists hints to configuring some common browsers or
mail programs.

** Gmail and Chrome

To get Chrome to automatically open the message in Gmail, rather than 
in a desktop mailer, follow these instructions from Google:

https://support.google.com/chrome/bin/answer.py?hl=en&answer=1382847&p=ib_protocol_handler

** Outlook

Outlook uses the semicolon as the address separator rather than the
standard comma. The workaround is to toggle the =Allow comma as
address separator= option in Outlook, as described here
<http://support.microsoft.com/kb/820868>.

** Internet Explorer 6/7/8

IE8 or earlier are not supported. You'll unfortunately need to do one of:

- Upgrade to IE9
- Install another browser
- Install the Chrome Frame plugin from http://www.google.com/chromeframe

